model_repository: models
models:
  rembg_preprocessing:
    engine: python
    max_batch_size: 0
    instance_group:
      - kind: cpu
    versions:
      - version: 1
        module:
          path: ./resources/rembg_preprocess.py
          execute: rembg_preprocess_processing
          initialize: rembg_preprocess_initialize
    tensor:
      input:
        - dims: [1, 320, 320, 3]
          dtype: uint8
      output:
        - dims: [1, 3, 320, 320]
          dtype: float32

  rembg_model:
    engine: onnx
    max_batch_size: 0
    instance_group:
      - kind: cpu
    versions:
      - version: 1
        path: ./resources/u2net.onnx

  rembg_postprocessing:
    engine: python
    max_batch_size: 0
    instance_group:
      - kind: cpu
    versions:
      - version: 1
        module:
          path: ./resources/rembg_postprocess.py
          execute: rembg_postprocess_processing
    tensor:
      input:
        - dims: [1, 1, 320, 320]
          dtype: float32
      output:
        - dims: [320, 320]
          dtype: uint8

  rembg:
    engine: ensemble
    max_batch_size: 0
    selector_ui: true
    steps:
      - model: rembg_preprocessing
        version: latest
      - model: rembg_model
        version: latest
      - model: rembg_postprocessing
        version: latest

  vqa:
    engine: python
    max_batch_size: 4
    instance_group:
      - kind: cpu
    versions:
      - version: 1
        module:
          path: ./resources/vqa.py
          execute: vqa_processing
    tensor:
      input:
        - dims: [-1, -1, 3]
          dtype: uint8
        - dims: [1]
          dtype: string
      output:
        - dims: [1]
          dtype: string

requirements:
  - Pillow
  - torch
  - transformers
