def get_docker_template(): return '''# Dockerfile for Deploy Triton Server.
# Auto generated by `trsp` module. Developed by Ming-doan.
# ------------------------------

FROM nvcr.io/nvidia/tritonserver:23.12-py3

'''
